# docker compose --env-file ./.env.test  up
version: '1.0'
services:
### MySQL Container
  mysql-planning-poker:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env.test 
    ports:
      - ${MYSQL_PORT}:3306
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}